global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_native_histograms: true
otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes: [service.name, service.namespace, service.instance.id]
storage:
  tsdb:
    out_of_order_time_window: 10m
scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: [cadvisor:8080]
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_project]
        regex: iaew-clase07|iaew07-validacion
        action: keep
      - source_labels: [container_label_com_docker_compose_service]
        target_label: compose_service
